project:
  type: website
  output-dir: docs
  resources:
    - "*.csv"
    - aviation.csv
    - shipping_small.csv

website:
  title: "IOSW project"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "+++ Deadline for the handover is the 09. October  +++"
    position: below-navbar
    type: warning
  navbar:
    backround: true
    search: true

    left:
      - href: index.qmd
        text: Home
      - href: python_installation.qmd
        text: Install Python 
      - text: Projects
        menu:
         
            - text: Python Basics
              href: introduction_python.ipynb
            - href: pandas.ipynb
              text: Pandas
            - href: Workflow.qmd
              text: Analysis Workflow
            - href: case_study.ipynb
              text: Case Study
   
      - href: data.qmd
        text: Data
   

           
       
     
            
      - href: about.qmd
        text: About
      - href: general.qmd 
        text: General Informations
    
      
      

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true